# Site settings
title: Wei Jiangang's Blog
email: weijg.fnst@cn.fujitsu.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a software engineer of fujitsu,
  and also a devotee and contributor for opensource.
  working on virtualization, autotest, kernel, etc.

  This's my personal tech-blog,
  But might post my attitude and feelings towards life. ^_^

  If you have any other inquires, questions, comments, ideas, etc, 
  feel free to contact me and I will do my best to respond.

  The website cloned from 3-Jekyll theme, licensed under CC BY-NC-SA.
  All rights for blog articles reserved.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://pandawei.github.io" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'


# Social account
# twitter:  username
# weibo:    ID
github:   PandaWei
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: discussion_shortname


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
